[package]
name = "dbms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.2.1"
chrono = "0.4.19"
log = "0.4.17"
bincode = "2.0.0-rc.1"
rand = "0.8.5"